spring:
  profiles:
    active: mongo
    # 프로필 활성화


---
spring:
  config:
    activate:
      on-profile: mongo
      #mongo 활성화 상태에서만

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb: DEBUG  # MongoDB 쿼리 로그 보기
    root: INFO

---
## 본 사이트 url
recipe:
  sites:
    okitchen:
      url: "https://www.okitchen.co.kr/category/detail?idx="
      collection-name: "okitchen-data"
    recipe10000:
      url: "https://www.10000recipe.com"
      collection-name: "recipe-10000-data"
    menupan:
      url: "https://www.menupan.com/Cook/recipeview.asp?cookid={}"
      collection-name: "menupan-data"
    samyang:
      url: "https://m.serveq.co.kr/"
      collection-name: "samyang-data"
    hansik:
      url: "https://www.hansik.or.kr/board/re/view/323?bbsSeq={}&bbsId=323&curPage=1&bbsType=re&menuSn=193&fdSe=&flag=N&searchWord="
      collection-name: "hansik-data"


---
## 인덱스 관련
recipe:
  indexUrl:
    recipe10000:
      url: "https://www.10000recipe.com/issue/view.html?cid=gdubu33&types=magazine&page="
      collection-name: "index-index10000"
      css-selector: "div.theme_list.st2 a.thumbnail"
    hansik:
      url: "https://www.hansik.or.kr/board/re/list/323?bbsSeq=&bbsId=323&curPage={}&bbsType=re&menuSn=193&fdSe=&flag=N&searchWord="
      collection-name: "testHansik"
      css-selector: "a.stretched-link"
    samyang:
      url: "https://m.serveq.co.kr/recipe/board/list.html?board_no={}&page="
      collection-name: "testSamYang"
      css-selector: "a.subject"
    menu-pan:
      url: "https://www.menupan.com/Cook/recipere.asp?difficulty={}&page="
      collection-name: "testMenuPan"
      css-selector: "span.link a"


